baseURL = '/'
languageCode = 'sr-RS'
title = 'Pribislav Hipe'
theme = 'paper'
# This stops Hugo from creating /tags/xxx pages completely
disableKinds = ["taxonomy", "term"]

# --- NEW PAGINATION SETTING ---
# This fixes the error you saw
[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

# --- MENU SETTINGS ---
[menu]
  [[menu.main]]
    identifier = "poezija"
    name = "Poezija"
    url = "/poezija/"
    weight = 10

  [[menu.main]]
    identifier = "proza"
    name = "Proza"
    url = "/proza/"
    weight = 20

  [[menu.main]]
    identifier = "o-meni"
    name = "O Autoru"
    url = "/o-autoru/"
    weight = 30


[params]
  customCSS = ["css/custom.css"]